name: Playwright Scrap and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Install Python dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          python -m playwright install

      # Run main.py script
      - name: Run main Python script
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: python main.py

      # Render Quarto site
      - name: Render Quarto site
        run: quarto render

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
