name: Playwright Scrap and Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write  # Ensure the workflow can push to the repository

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          python -m playwright install

      - name: Run main Python script
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: python main.py

      - name: Install Quarto CLI
        run: |
          wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.6.3/quarto-1.6.3-linux-amd64.deb
          sudo apt-get update -y
          sudo apt-get install -y ./quarto-1.6.3-linux-amd64.deb
          rm quarto-1.6.3-linux-amd64.deb  # Delete the .deb file to prevent committing

      - name: Render Quarto site
        run: quarto render

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site  # Replace with your Quarto output directory
          publish_branch: gh-pages
          force_orphan: true  # Optional: creates a new commit history on gh-pages
