name: Playwright scrap

# Run the workflow on pushes to the main branch and pull requests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define the jobs that will run
jobs:
  test:
    # Define the operating system and environment
    runs-on: ubuntu-latest

    # Define the steps
    steps:
      # Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # You can specify the Node.js version you need
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Specify your Python version
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          python -m playwright install   
      - name: Run Python script
        run: python main.py
