name: Playwright Scrap and Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          python -m playwright install

      - name: Run main Python script
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: python main.py

      - name: Install Quarto CLI
        run: |
          wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.6.3/quarto-1.6.3-linux-amd64.deb
          sudo apt-get update -y
          sudo apt-get install -y ./quarto-1.6.3-linux-amd64.deb

      - name: Verify Quarto Installation
        run: |
          which quarto
          quarto --version
          quarto check install

      - name: Render Quarto site
        run: quarto render

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
